---
- name: Copy plugins to server
  copy:
    #src: "{{ srcdir }}/{{ item.plugin_src | basename }}"
    src: "{{ item.plugin_src }}"
    dest: "{{ item.plugin_dst }}"
    owner: root
    group: root
    mode: 0755
  when:
    - not ansible_check_mode
    - cmkclient_plugins is defined
  with_items: "{{ cmkclient_plugins }}"
