- name: Deploy SSH publickey for monitoring user
  authorized_key:
    user: "{{ cmkclient_user.name }}"
    manage_dir: yes
    exclusive: yes
    state: present
    key: "{{ cmkclient_user.publickey }}"
